### ISSUE TITLE
The build is fail in ios

### ISSUE THREAD

**Issue by roysG** [wix/list-view-experiments#7]
/Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: error:
    ignoring return value of function declared with warn_unused_result
    attribute [-Werror,-Wunused-result]
SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);
^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1334:5: error:
    ignoring return value of function declared with warn_unused_result
    attribute [-Werror,-Wunused-result]
SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);
^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.

=== BUILD TARGET RCTImage OF PROJECT RCTImage WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
write-file /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage.hmap
write-file /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-all-target-headers.hmap
write-file /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-own-target-headers.hmap
/bin/mkdir -p /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64
write-file /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTImage.LinkFileList
write-file /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-project-headers.hmap
write-file /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-generated-files.hmap
write-file /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-all-non-framework-target-headers.hmap

CompileC /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTVirtualImageManager.o RCTVirtualImageManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
cd /Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/Libraries/Image
export LANG=en_US.US-ASCII
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/user1/Downloads/android-sdk-macosx//tools:/Users/user1/Downloads/android-sdk-macosx//platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=78 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=7.0 -g -Wno-sign-conversion -Wno-infinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-generated-files.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-own-target-headers.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-all-target-headers.hmap -iquote /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-project-headers.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I../../React -I../../React/Base -I../../React/Executors -I../../React/Layout -I../../React/Modules -I../../React/Profiler -I../../React/Views -I../Network -I../Network/__tests__ -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/DerivedSources/x86_64 -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/DerivedSources -Werror -Wall -F/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTVirtualImageManager.d --serialize-diagnostics /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTVirtualImageManager.dia -c /Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/Libraries/Image/RCTVirtualImageManager.m -o /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTVirtualImageManager.o

CompileC /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTImageStoreManager.o RCTImageStoreManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
cd /Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/Libraries/Image
export LANG=en_US.US-ASCII
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/user1/Downloads/android-sdk-macosx//tools:/Users/user1/Downloads/android-sdk-macosx//platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=78 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=7.0 -g -Wno-sign-conversion -Wno-infinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-generated-files.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-own-target-headers.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-all-target-headers.hmap -iquote /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-project-headers.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I../../React -I../../React/Base -I../../React/Executors -I../../React/Layout -I../../React/Modules -I../../React/Profiler -I../../React/Views -I../Network -I../Network/__tests__ -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/DerivedSources/x86_64 -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/DerivedSources -Werror -Wall -F/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTImageStoreManager.d --serialize-diagnostics /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTImageStoreManager.dia -c /Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/Libraries/Image/RCTImageStoreManager.m -o /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTImageStoreManager.o

CompileC /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTImageViewManager.o RCTImageViewManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
cd /Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/Libraries/Image
export LANG=en_US.US-ASCII
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/user1/Downloads/android-sdk-macosx//tools:/Users/user1/Downloads/android-sdk-macosx//platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=78 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=7.0 -g -Wno-sign-conversion -Wno-infinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-generated-files.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-own-target-headers.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-all-target-headers.hmap -iquote /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-project-headers.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I../../React -I../../React/Base -I../../React/Executors -I../../React/Layout -I../../React/Modules -I../../React/Profiler -I../../React/Views -I../Network -I../Network/__tests__ -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/DerivedSources/x86_64 -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/DerivedSources -Werror -Wall -F/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTImageViewManager.d --serialize-diagnostics /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTImageViewManager.dia -c /Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/Libraries/Image/RCTImageViewManager.m -o /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTImageViewManager.o

CompileC /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTGIFImageDecoder.o RCTGIFImageDecoder.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
cd /Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/Libraries/Image
export LANG=en_US.US-ASCII
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/user1/Downloads/android-sdk-macosx//tools:/Users/user1/Downloads/android-sdk-macosx//platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=78 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=7.0 -g -Wno-sign-conversion -Wno-infinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-generated-files.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-own-target-headers.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-all-target-headers.hmap -iquote /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/RCTImage-project-headers.hmap -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I../../React -I../../React/Base -I../../React/Executors -I../../React/Layout -I../../React/Modules -I../../React/Profiler -I../../React/Views -I../Network -I../Network/__tests__ -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/DerivedSources/x86_64 -I/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/DerivedSources -Werror -Wall -F/Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTGIFImageDecoder.d --serialize-diagnostics /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTGIFImageDecoder.dia -c /Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/Libraries/Image/RCTGIFImageDecoder.m -o /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTGIFImageDecoder.o

** BUILD FAILED **

The following build commands failed:
    CompileC /Users/user1/www/letsGout/fixScroll/list-view-experiments/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
    Provide a valid path to the desired application bundle.
    Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/promise/lib/done.js:10
throw err;
^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

at checkExecSyncError (child_process.js:483:13)
at Object.execFileSync (child_process.js:503:13)
at _runIOS (/Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/local-cli/runIOS/runIOS.js:91:34)
at /Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
at tryCallTwo (/Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/promise/lib/core.js:45:5)
at doResolve (/Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/promise/lib/core.js:200:13)
at new Promise (/Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/promise/lib/core.js:66:3)
at Array.runIOS (/Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
at Object.run (/Users/user1/www/letsGout/fixScroll/list-view-experiments/node_modules/react-native/local-cli/cli.js:87:13)
at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
Roys-MacBook-Pro:list-view-experiments user1$

**Comment by powercoder23** [comment]
Any update on this, I am facing the same issue
